---
version: "3"

services:
  mysqldb:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Admin#123
    networks:
      - mysql_network
    deploy:
      placement:
        constraints: [node.role == manager]
  python-application:
    image: naresh240/python_app:v1
    ports:
      - 5000:5000
    networks:
      - mysql_network
    deploy:
      replicas: 3
      placement:
        constraints:
          - node.role == worker
volumes:
    db_data: {}

networks:
  mysql_network:
    driver: overlay
